name: Build Linux Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: ray-configurator-${{ github.sha }}
        path: dist/linux